import type { Metadata } from "next";
import LegalShell from "../legal-shell";

export const metadata: Metadata = {
  title: "Privacy Policy | PatientTrac Limited",
  description: "How PatientTrac Limited handles personal information associated with its corporate website.",
};

export default function PrivacyPage() {
  return (
    <LegalShell
      eyebrow="Privacy"
      title="Privacy Policy"
      summary="This policy explains how PatientTrac Limited handles personal information associated with this website and direct communications."
    >
      <section>
        <h2>1. Who we are</h2>
        <p>
          PatientTrac Limited is the controller of personal information described
          in this policy. Our Corporate Headquarters are at 1 Gracechurch Street,
          5th Floor, London, England EC3V 0DD. Privacy enquiries may be sent to
          <a href="mailto:legal@patienttracltd.com"> legal@patienttracltd.com</a>.
        </p>
      </section>

      <section>
        <h2>2. Scope</h2>
        <p>
          This policy applies to visitors to patienttracltd.com and people who
          contact us using the email address or telephone number published on the
          Site. It does not govern third-party websites or services linked from
          the Site.
        </p>
      </section>

      <section>
        <h2>3. Information we collect</h2>
        <ul>
          <li><strong>Information you provide:</strong> your name, contact details, organisation, role, and the content of communications you send us.</li>
          <li><strong>Technical information:</strong> IP address, browser and device information, requested pages, timestamps, referring page, and security or diagnostic records generated by our hosting infrastructure.</li>
          <li><strong>Business relationship information:</strong> correspondence, meeting notes, engagement history, and records needed to manage an enquiry or professional relationship.</li>
        </ul>
        <p>
          Please do not send special-category personal information, confidential
          transaction materials, or other sensitive information through an
          unsolicited website enquiry.
        </p>
      </section>

      <section>
        <h2>4. Why we use information</h2>
        <div className="legal-table-wrap">
          <table>
            <thead><tr><th>Purpose</th><th>Typical lawful basis</th></tr></thead>
            <tbody>
              <tr><td>Respond to enquiries and take requested pre-contract steps</td><td>Steps at your request before a contract; legitimate interests</td></tr>
              <tr><td>Manage business and professional relationships</td><td>Performance of a contract; legitimate interests</td></tr>
              <tr><td>Operate, secure, and improve the Site</td><td>Legitimate interests in reliable and secure systems</td></tr>
              <tr><td>Keep records and meet legal or regulatory requirements</td><td>Legal obligation; legitimate interests</td></tr>
              <tr><td>Establish, exercise, or defend legal claims</td><td>Legitimate interests; applicable legal provisions</td></tr>
            </tbody>
          </table>
        </div>
        <p>
          Where we rely on legitimate interests, we consider the purpose,
          necessity, and impact on your rights. Where consent is required, you may
          withdraw it at any time without affecting earlier lawful processing.
        </p>
      </section>

      <section>
        <h2>5. Sharing information</h2>
        <p>We may share personal information, where appropriate, with:</p>
        <ul>
          <li>hosting, security, communications, and professional service providers acting for us;</li>
          <li>legal, accounting, regulatory, insurance, and other professional advisers;</li>
          <li>public authorities or courts where disclosure is required or permitted by law; and</li>
          <li>parties involved in a genuine corporate transaction, subject to appropriate confidentiality protections.</li>
        </ul>
        <p>We do not sell personal information.</p>
      </section>

      <section>
        <h2>6. International transfers</h2>
        <p>
          Some service providers may process information outside the United
          Kingdom. Where required, we use an approved transfer mechanism and
          appropriate safeguards, and assess supplementary measures relevant to
          the transfer.
        </p>
      </section>

      <section>
        <h2>7. Retention</h2>
        <p>
          We retain information only for as long as reasonably necessary for the
          purpose collected, including to respond to enquiries, manage
          relationships, meet legal and regulatory duties, resolve disputes, and
          enforce agreements. Retention periods vary according to the record and
          applicable requirements.
        </p>
      </section>

      <section>
        <h2>8. Your rights</h2>
        <p>
          Depending on the circumstances, UK data protection law may give you the
          right to request access, correction, erasure, restriction, or portability
          of your personal information, and to object to certain processing. You
          may also withdraw consent where consent is the lawful basis.
        </p>
        <p>
          To exercise a right, email
          <a href="mailto:legal@patienttracltd.com"> legal@patienttracltd.com</a>.
          We may need information to verify your identity. You may complain to the
          <a href="https://ico.org.uk/make-a-complaint/data-protection-complaints/" target="_blank" rel="noreferrer"> Information Commissioner’s Office</a>.
        </p>
      </section>

      <section>
        <h2>9. Security</h2>
        <p>
          We use proportionate technical and organisational measures intended to
          protect personal information. No internet transmission or storage system
          is completely secure, and we cannot guarantee absolute security.
        </p>
      </section>

      <section>
        <h2>10. Cookies and similar technologies</h2>
        <p>
          The current Site does not use advertising or behavioural analytics
          cookies. Our hosting and security providers may use strictly necessary
          technologies to deliver the Site, balance traffic, and protect against
          misuse. If we introduce optional analytics or marketing technologies,
          we will update this policy and request consent where required.
        </p>
      </section>

      <section>
        <h2>11. Children</h2>
        <p>
          The Site is intended for a business audience and is not directed to
          children under 18. We do not knowingly collect children’s personal
          information through the Site.
        </p>
      </section>

      <section>
        <h2>12. Changes and contact</h2>
        <p>
          We may update this policy to reflect changes in law, technology, or our
          practices. The current version and effective date will remain available
          on this page. Questions may be sent to legal@patienttracltd.com or to
          our Corporate Headquarters at 1 Gracechurch Street, 5th Floor, London,
          England EC3V 0DD.
        </p>
      </section>
    </LegalShell>
  );
}
